# Aim to have fast builds
# TODO: Don't build the files into seperate folders and copy them after that anyway.
# TODO: Stage another download (parallel) that contains uncommon resolutions.

language: php

php:
  - 7.0

git:
  depth: 1
  submodules: false

branches:
  only:
    - master
  except:
    - /build-.+-\d{4}-\d{2}-\d{2}-.*/

# Simultaneous builds for common and uncommon resolutions
env:
  matrix:
    - buildType=Common
    - buildType=Uncommon
  global:
    - secure: "GBdfAmN1q45grcomyEMeFWyj9sP3t147oO60O5M1jdnXk+1wKf8x7MMp6/RTzTUioKTRtXn6RoCSQOgqQtacSwVg1X97UCczr50i49SLZ3IEeP9g3gAvEfa9KZN3QZa6Sb79xTuOggLiF8POpC5ow8ZPnbaD1CQlLA/z+YaOYmMym69WLE5v5gJRuoXVQFHbbWKYkCCUP8wZ2Bp5bgxgeRuSNSUmWRJJdtzmuEYcPMHDuQ0LYSNr8XM7+1O/UOXeSHfIl5Y7RD8wogXbq7B2xF34TPLMBVPQVzuOyuD0Nrf9TCL6uiEmGr3B8tTGgVquP6YPfiLIlchb/o9rxB+LL/EURfVy73ZaaTiDaOQKxCXdds0+riA3NoJduAETbbH6yLupRul8WawsO6iKL0yKSwHesgBBtT61ZrQRXsUmGtIyrPLosfp/vzOQ6b5rjS7zkabl3W73K1J46IEiZu30S7pjC7jYR78h/Kxiypg1jk3awXXS67Yp3AGvkLIp2RNouX1ja3KI+UObM6dkexDD0xpKypvTHWsZ6XQdqYhJthSVGGDP3jDbTFS4drrpayNLNljIE3hX5PXae3m+swLr0F3bxD4w2Vvo7cFfJ76119amhGavQ1USNuDnMvrPxeL5gW3vkXBT5YoSXegdAbhXlZ7dgJmRoG4om8eL78QUFp8=" # GITHUB_TOKEN

matrix:
  fast_finish: true

# === Build steps ===

# No dependencies
install: npm install -g github-release-cli

# No need to debug the PHP code. Would slow down execution
before_script:
  - phpenv config-rm xdebug.ini

script: ./build.sh

before_deploy:
  # Create zip file
  - mkdir build
  - mv $TRAVIS_BUILD_DIR/Enhancement/* build
  - mv $TRAVIS_BUILD_DIR/Enthusiast/* build
  - mv $TRAVIS_BUILD_DIR/Modifications/* build
  - mv $TRAVIS_BUILD_DIR/Performance/* build
  - mv $TRAVIS_BUILD_DIR/Quality/* build
  - mv $TRAVIS_BUILD_DIR/Workaround/* build
  - cd build
  - zip -o -9 -r -q ../graphicPacks$buildType_$TRAVIS_BUILD_NUMBER.zip ./*

after_success:
  - |
    github-release upload \
      --owner=Crementif \
      --repo=cemu_graphic_packs \
      --tag="Travis$TRAVIS_BUILD_NUMBER" \
      --name="Graphic Packs: version $TRAVIS_BUILD_NUMBER" \
      --body="$(git log -1 --format='Commited at %ci by **%cn** in commit %h%n### %s%n```%n%b%n```')" \
      "graphicPacks$buildType_$TRAVIS_BUILD_NUMBER.zip"