# Aim to have fast builds
# TODO: Don't build the files into seperate folders and copy them after that anyway.
# TODO: Stage another download (parallel) that contains uncommon resolutions.

language: php

php:
  - 7.0

git:
  depth: 1
  submodules: false

branches:
  only:
    - master
  except:
    - /build-.+-\d{4}-\d{2}-\d{2}-.*/

# Simultaneous builds for common and uncommon resolutions
env:
  - buildType=Common
  - buildType=Uncommon

matrix:
  fast_finish: true

# === Build steps ===

# No dependencies
install: npm install -g github-release-cli

# No need to debug the PHP code. Would slow down execution
before_script:
  - phpenv config-rm xdebug.ini

script: ./build.sh

before_deploy:
  # Create zip file
  - mkdir build
  - mv $TRAVIS_BUILD_DIR/Enhancement/* build
  - mv $TRAVIS_BUILD_DIR/Enthusiast/* build
  - mv $TRAVIS_BUILD_DIR/Modifications/* build
  - mv $TRAVIS_BUILD_DIR/Performance/* build
  - mv $TRAVIS_BUILD_DIR/Quality/* build
  - mv $TRAVIS_BUILD_DIR/Workaround/* build
  - cd build
  - zip -o -9 -r -q ../graphicPacks$buildType_$TRAVIS_BUILD_NUMBER.zip ./*

after_success:
  - |
    github-release upload \
      --owner=Crementif \
      --repo=cemu_graphic_packs \
      --tag="Travis$TRAVIS_BUILD_NUMBER" \
      --name="Graphic Packs: version $TRAVIS_BUILD_NUMBER" \
      --body="$(git log -1 --format='Commited at %ci by **%cn** in commit %h%n### %s%n```%n%b%n```')" \
      "graphicPacks$buildType_$TRAVIS_BUILD_NUMBER.zip"