name: Build Graphic Packs

# Don't bother creating releases in some cases
on: [push, pull_request]

jobs:
  build:
    # Configuration
    runs-on: ubuntu-latest
    name: Build
    
    # Build script
    steps:
    # Clone latest copy of repository
    - uses: actions/checkout@v1
      with:
        fetch-depth: 10
    - name: Zip all packs
      run: |
        cd $GITHUB_WORKSPACE |
        cd Enhancements && zip -r -q -9 "../graphicPacks.zip" ./* && cd .. |
        cd Resolutions && zip -r -q -9 "../graphicPacks.zip" ./* && cd .. |
        cd Mods && zip -r -q -9 "../graphicPacks.zip" ./* && cd .. |
        cd Workarounds && zip -r -q -9 "../graphicPacks.zip" ./* && cd ..
    - name: Create new release
#      if: github.event == 'push'
      run: |
        RELEASENUMBER=$(git describe --tags) |
        echo The title of this release should be $RELEASENUMBER
        
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
